//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTrackerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBudget
    {
        public int BudgetId { get; set; }
        public string UserId { get; set; }
        public bool IsAccepted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Budget Budget { get; set; }
    }
}
