//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTrackerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetGoal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BudgetGoal()
        {
            this.CategoryGoals = new HashSet<CategoryGoal>();
        }
    
        public int BudgetGoalId { get; set; }
        public int BudgetId { get; set; }
        public string TimePeriod { get; set; }
        public decimal BudgetAmount { get; set; }
        public bool IsProgressBarEnabled { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual Budget Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryGoal> CategoryGoals { get; set; }
    }
}
