//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTrackerApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyBudgetTrackerAppEntities : DbContext
    {
        public MyBudgetTrackerAppEntities()
            : base("name=MyBudgetTrackerAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetGoal> BudgetGoals { get; set; }
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<PeriodicIncome> PeriodicIncomes { get; set; }
        public virtual DbSet<AccountBudget> AccountBudgets { get; set; }
        public virtual DbSet<CategoryGoal> CategoryGoals { get; set; }
    }
}
