//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTrackerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryGoal
    {
        public int CategoryId { get; set; }
        public int BudgetGoalId { get; set; }
        public decimal BudgetAmount { get; set; }
    
        public virtual BudgetGoal BudgetGoal { get; set; }
        public virtual Category Category { get; set; }
    }
}
